site_name: Bioinformatics and computational approaches in Microbiology
nav:
    - Home: index.md
    - Precourse preparations: precourse.md
    - Course schedule: course_schedule.md
    - Project 1: project1.md
    - Project 2: 
      - Description: project2.md
      - Preparation: project2/Prepare-before-start-of-the-course.md
      - Project 0: project2/Project-0.md
      - Project 1: project2/Project-1.md
      - Project 2: project2/project-2.md
    - Project 3:
      - Description: project3.md
      - Preparation: project3/Prepare-before-start-of-the-course.md
      - Overview: project3/Overview.md
      - Step 1: project3/Step-1.md
      - Step 2: project3/Step-2.md
    - Project 4: project4.md

theme:
  name: material
  icon: 
    logo: material/bacteria
  favicon: assets/images/bacteria.png
  palette:
    primary: grey
    accent: red


# Repository
repo_name: sib-swiss/spring_school_bioinformatics_microbiology
repo_url: https://github.com/sib-swiss/spring_school_bioinformatics_microbiology

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# extra_css:
#   - stylesheets/extra.css
