channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - fastqc=0.11.9
  - trimmomatic=0.39
  - mapseq=1.2.6
  - samtools=1.12
  - bwa
  - metasnv 
  - ipykernel
  - pip
  - pip:
    - motu-profiler
